pipeline:
  name: "remotePms"
  identifier: "remotePms"
  projectIdentifier: "TcSvcOverrideTest"
  orgIdentifier: "default"
  tags: {}
  stages:
  - stage:
      name: "s2"
      identifier: "s1"
      description: ""
      type: "Deployment"
      spec:
        deploymentType: "Kubernetes"
        service:
          serviceRef: "<+input>"
          serviceInputs: "<+input>"
        environment:
          environmentRef: "<+input>"
          deployToAll: false
          environmentInputs: "<+input>"
          infrastructureDefinitions: "<+input>"
        execution:
          steps:
          - step:
              name: "Rollout Deployment"
              identifier: "rolloutDeployment"
              type: "K8sRollingDeploy"
              timeout: "10m"
              spec:
                skipDryRun: false
                pruningEnabled: false
          rollbackSteps:
          - step:
              name: "Rollback Rollout Deployment"
              identifier: "rollbackRolloutDeployment"
              type: "K8sRollingRollback"
              timeout: "10m"
              spec:
                pruningEnabled: false
      tags: {}
      failureStrategies:
      - onFailure:
          errors:
          - "AllErrors"
          action:
            type: "StageRollback"
  - stage:
      name: "s2"
      identifier: "s2"
      template:
        templateRef: "stagetemp3"
        versionLabel: "1"
        templateInputs:
          type: "Deployment"
          spec:
            execution:
              steps:
              - step:
                  identifier: "tcss"
                  template:
                    templateInputs:
                      type: "ShellScript"
                      timeout: "<+input>"
